# Generated by Django 4.0.3 on 2022-05-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
        ('posts', '0004_alter_post_name'),
    ]

    operations = [
    ]
