# Generated by Django 4.0.3 on 2022-05-24 19:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20220224_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isrecomendedforyou',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selectedforyou',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='Name'),
        ),
    ]
